### ISSUE TITLE
本当にmasterに直接プッシュできないか確認する

### ISSUE THREAD

**Issue by ito-hit** [ito-hit/pullRequest_test#3]
中尾さんのPCにて確認してもらう。

**Comment by nakao-hit** [comment]
GitHubで”ito-hit~~~”にプッシュするためのアクセスする許可がありません。代わりに、フォークを作成してそれにプッシュしますか？
というメッセージでした

**Comment by ito-hit** [comment]
https://aisumegane.com/github_vscode_you-do-not-have-permission-to-push-to-on-github_gitgraph_vscode/
このサイトが参考になるかも？
さっきブラウザでgithubにログインしようとしたときsakamotoでログインしようとしてたから坂元さんのアカウントでpushしようとしてしまってる？
他の人に入ってもらってpush出来たら中尾さんのpcの設定がおかしい証明ができるけど・・・

**Comment by nakao-hit** [comment]
![スクリーンショット 2024-07-10 100332](https://github.com/ito-hit/pullRequest_test/assets/172765080/e610a594-fb38-4b45-bef5-7bd04645454e)
nakaoのはずなんですけどね

**Comment by ito-hit** [comment]
そうですね～
とりあえずmasterのルールは外したけど現象は変わらないかな？

**Comment by nakao-hit** [comment]
再度クローンしましたが変わらないですね

**Comment by ito-hit** [comment]
中尾さんのアカウントでもプッシュはできた。
マスターにプッシュはできなくなっているのでこのissueはクローズします。
